### ISSUE TITLE
How to handle arrays of objects

### ISSUE THREAD

**Issue by lauglam** [wopehq/muninn#74]
# How to handle arrays of objects

## This is my html

```html
<!DOCTYPE >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head> </head>
  <body>
    <div>
      <table>
        <tr>
          <td>
            <p><a href="#" onclick="return do_hathdl('780')">780x</a></p>
          </td>
          <td>
            <p><a href="#" onclick="return do_hathdl('980')">980x</a></p>
          </td>
        </tr>
      </table>
    </div>
  </body>
</html>
```

## This is my config

```text
{
  schema: {
    items: {
      // What should I do ?
      type: "array",
      regex: new RegExp(
        '<a href="[^"]*" onclick="return do_hathdl\\(\'([0-9]+|org)\'\\)">([^<]+)</a>',
      ),
    },
  },
}
```

## Expect

```json
{
  "items": [
    {
      "res": "780",
      "name": "780x"
    },
    {
      "res": "980",
      "name": "980x"
    }
  ]
}
```

**Comment by aykutkardas** [comment]
You have to give the repeating element as a selector. `(tr td)`

For this case and more, take a look at the simplified document.
https://wopehq.gitbook.io/muninn/config/array


**Config:**
```js
{
  schema: {
    items: {
      selector: "tr td | html | array",
      transform: (val) => {
        const result = new RegExp(
          '<a href="[^"]*" onclick="return do_hathdl\\(\'([0-9]+|org)\'\\)">([^<]+)</a>'
        ).exec(val);

        return {
          res: result?.[1],
          name: result?.[2],
        };
      },
    },
  },
}
```

**Comment by lauglam** [comment]
> You have to give the repeating element as a selector. `(tr td)`
> 
> For this case and more, take a look at the simplified document. https://wopehq.gitbook.io/muninn/config/array
> 
> **Config:**
> 
> ```js
> {
>   schema: {
>     items: {
>       selector: "tr td | html | array",
>       transform: (val) => {
>         const result = new RegExp(
>           '<a href="[^"]*" onclick="return do_hathdl\\(\'([0-9]+|org)\'\\)">([^<]+)</a>'
>         ).exec(val);
> 
>         return {
>           res: result?.[1],
>           name: result?.[2],
>         };
>       },
>     },
>   },
> }
> ```

```text
selector: "tr td | html | array"
```

Can a selector contain other config? Wow, that's cool. Thanks for telling me.

**Comment by aykutkardas** [comment]
> Can a selector contain other config? Wow, that's cool. Thanks for telling me.

Yes, it can.

Also, you can write the same config like this.


```js
{
  schema: {
    items: {
      selector: "tr td | array",
      schema: {
        name: 'a',
        res: {
          selector: 'a @ onclick',
          transform: (val) => new RegExp('\\(\'([0-9]+|org)\'\\)').exec(val) ? . [1]
        },
      },
    },
  },
}
```
